### ISSUE TITLE
Kismet with different user directory

### ISSUE THREAD

**Issue by zokl** [kismetwireless/kismet-packages#2]
Hello,

I try to make a Kismet server init script for OpenWRT. I would like to change default user data storage from ~/.kismet to a different place. I try to run Kismet with parameters --confdir/homedir but without success. Kismet still uses the user's home dir location. 

Do you know what is wrong? I used Kismet 2020-12-R3.

Thank you.

**Comment by kismetwireless** [comment]
You'd have to override the config directory in kismet.conf (or preferably kismet_site.conf)

-------- Original Message --------

**Comment by zokl** [comment]
> You'd have to override the config directory in kismet.conf (or preferably kismet_site.conf)
> […](#)

Thank you I will try it.

**Comment by zokl** [comment]
By the way, the problem was in OpenWRT PROCD init file and the definition of append command params. It is necessary to put commands without quotation marks.
